import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/home1">HOME1</Link>
        </li>
        <li>
          <Link to="/study">STUDY</Link>
        </li>
        <li>
          <Link to="/about">ABOUT</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/testimonials">Testimonials</Link>
        </li>
        <li>
          <Link to="/dashboardadmin">DashboardAdmin</Link>
        </li>
        <li>
          <Link to="/dashboardadmintwo">DashboardAdminTwo</Link>
        </li>
        <li>
          <Link to="/dashboardadminfour">DashboardAdminFour</Link>
        </li>
        <li>
          <Link to="/dashboardadminthree">DashboardAdminThree</Link>
        </li>
        <li>
          <Link to="/dashboardadminfive">DashboardAdminFive</Link>
        </li>
        <li>
          <Link to="/dashboardadminlessonhome">DashboardAdminlessonhome</Link>
        </li>
        <li>
          <Link to="/dashboardadminone">DashboardAdminOne</Link>
        </li>
        <li>
          <Link to="/registerone">RegisterOne</Link>
        </li>
        <li>
          <Link to="/dashboardadminquize">DashboardAdminquize</Link>
        </li>
        <li>
          <Link to="/dashboardadminquizeone">DashboardAdminquizeOne</Link>
        </li>
        <li>
          <Link to="/dashboardadminread">DashboardAdminread</Link>
        </li>
        <li>
          <Link to="/joinfreeseminar">JoinFreeSeminar</Link>
        </li>
        <li>
          <Link to="/testimonialsone">TestimonialsOne</Link>
        </li>
        <li>
          <Link to="/learnkanjione">LearnkanjiOne</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/learnhiragana">LearnHiragana</Link>
        </li>
        <li>
          <Link to="/dashboardadminreadone">DashboardAdminreadOne</Link>
        </li>
        <li>
          <Link to="/learnkanji">Learnkanji</Link>
        </li>
        <li>
          <Link to="/news">News</Link>
        </li>
        <li>
          <Link to="/learnhiraganaone">LearnHiraganaOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
